# Generated by Django 5.2.1 on 2025-06-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('transfer', 'Chuyển khoản')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
